### ISSUE TITLE
Staff side menu

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#11]
Side menu looks good but you can't use two column on the staff page (coz you are using the staff listing template) so the side menu can't appear. Is this intentional? It seems like it might be a bit confusing to the user if they are making their way through the subsections of 'About' and then the side menu disappears.

**Comment by 1001hz** [comment]
New way to show the staff list. Instead of using the staff template just use the 2 column one. In the content put [staff] wherever you want the staff list to appear and it will be inserted (like the quote tag we already have). I'll do this on the site so just have a look to see what I mean. I made the staff list 1 column because 2 looked squashed

**Comment by aileennoonan** [comment]
Sounds great but I broke the staff menu somehow so I can't actually go in to look at it at the moment :)

**Comment by 1001hz** [comment]
You can get to staff now

**Comment by aileennoonan** [comment]
Great, thanks John. 

The sub menu/side menu isn't visible on the mobile version yet. As we chatted, it would be great if the sub menu/side menu appeared on the mobile version but not the desktop (as we have the top menu)

**Comment by 1001hz** [comment]
The reason it's not showing is because the About Us page had the single column template set. You need to use the 2 col template if you want the side menu to appear. I've changed it already so you should see it now.

**Comment by aileennoonan** [comment]
Thanks John.. The side menu looks so good on mobile. One question though... the sub items in About Us are showing up in a different order than they should. It should be About Us - Our Team - FAQs but on the mobile sub menu it's showing up About Us - FAQs - Our Team. 

Any ideas as to why?

**Comment by 1001hz** [comment]
This is just the order they are in the backend. You can drag them around. I've already fixed them but you can move them again if you want by going to Pages in the backend and drag and drop to change the order.

**Comment by aileennoonan** [comment]
Okay.. I'm baffled as I did double check the order of them in the backend!! 

I obviously don't know my back end as well as my front end if you know what I mean ;)

You can close this off now!
