### ISSUE TITLE
Main menu adding items

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#12]
Why doesn't 'Another test page' appear under the drop down 'About' menu on the homepage? I've tried lots of different things and I can't get it to appear! It appears in the side menu.

**Comment by 1001hz** [comment]
You control the main nav using the menu area in wordpress. Go to Appearence -> Menu and select 'main-nav' if it's not already showing. You can add and remove items from the main menu here.

**Comment by aileennoonan** [comment]
Yup.. I have this figured out. But I'm not sure it's working fully well and sic. Due to the fact that Staff is divorced from About Us even though it looks fine in the appearance - menu- main nav back end.

**Comment by 1001hz** [comment]
Think this is sorted
