### ISSUE TITLE
Homepage contact icons

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#13]
Design changes: the 4 boxes above the map. I like the functionality and user friendlyness of this but I'm don't like the design on desktop as it's pretty massive in size and when you scroll down a tiny bit further there is more contact info again. I also think it's just too much blue. I dont think we need the fax in that quadrant though coz it's not functional. So.. I'm not sure what you need from me in order to change this? Do you have any other design ideas up your sleeve? I would prefer something more minamilist. Is it a bad idea to remove it completely and let the contact details in the footer serve this function? FYI In the footer the email address needs to be brought up beside the @ sign (it's fine on mobile).

**Comment by 1001hz** [comment]
Ok I've changed the desktop design a bit. See if you like it.

**Comment by aileennoonan** [comment]
You are a special kind of guy
