### ISSUE TITLE
Services images blue filter

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#14]
The images look good in the categories on the homepage. Maybe we could make the blue a little more see-through? You will see in the designer's mockup the image looks a little darker or more vivid behind the blue. Is there a way to have more control over which part of the image shows up? Some heads are being cut off and I just want to be able to move the focus of the image up a bit!

**Comment by 1001hz** [comment]
The images are now always going to show from the top and scale from there to stop any heads being cut off (some feet might get chopped though). AS for the blue filter on the images: I'm kind of limited with what I can do to images with CSS. It's not like photoshop. All I can do is put a color over the image and then make that overlay more or less see through. The images in the design have more processing done that I can't replicate exactly. If you have the actual images with these filters applied from photoshop then we can use them.

**Comment by aileennoonan** [comment]
Thank for fixing the head chopping. Don't worry about the blue filter thing... it looks great as it is. You can close this one off.
