### ISSUE TITLE
services listing page

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#16]
I'm not loving the services listing page yet but I think it's getting there:
     - Take the physiotherapy category for example. I think the list looks very long. Could we make them into 2 columns? With a blurb and the long list, the image looks tiny.. it just sorta looks unbalanced. I don't think I want to go looking for other examples coz I think this has the potential to work really well. It just needs a few teaks!

**Comment by 1001hz** [comment]
Moved the heading up above the picture to give the blurb and links more room. Using the same arrow concept on the heading that the services tabs on the homepage have.

**Comment by aileennoonan** [comment]
Hi John,

This is really looking great now (like.. REALLY GREAT!) Just to reiterate a few of the things we discussed last night:
- I need to have more control over the content in each of the service categories so if you could make it a wysiwyg that would be great. 
- It would also be sweet if the service categories could appear on the drop down menu under services. I added a new service category called orthotics and it worked great.. it appears on the services page, not on the homepage. It would be ideal if the extra service categories did appear on the drop down menu though.  

Byeeeeeeeeeee!

**Comment by 1001hz** [comment]
wysiwyg added.
I put in the menu items manually for services using custom links in the menu section. You can easily edit or move around.

**Comment by aileennoonan** [comment]
wysiwyg is perfect. 

Regarding the menu items, how do I get it to link automatically the section of the our services that I want it to? At the moment when you select women's health from the drop down menu  it goes to physiotherapy. How do I get it to go to Women's Health? 
I made up a new service category called 'Test Category' and managed to get it in the drop down menu but not automatically linking down to the area of page that I want it to.

**Comment by aileennoonan** [comment]
EEEEEEEEEE I figured this out myself!! Women's Health and Test Category perma links had dashes in them i.e. women's-health which didn't match the custom link in the menu section. I took the dash out of the perma link and hey presto it works!

**Comment by aileennoonan** [comment]
I think you can close this one now. The only other thing I might suggest is that the words 'Our Services' on the homepage might be made so it links to the our services page but only if you think this is a good idea. Maybe it's a terrible idea!

**Comment by 1001hz** [comment]
No that's fine but for consistency I made the other headings links also (About Us and Staff). Can close if you're happy with that

**Comment by aileennoonan** [comment]
Perfect! Thanks John.. happy for you to close.
