### ISSUE TITLE
I want to be able to use the ticks on the 'About Us' section of the homepage

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#21]
Can we make this a bit more WYSIWYG?:
![image](https://user-images.githubusercontent.com/25756782/26999319-0bad65f8-4dda-11e7-9107-ef6e606a2dc7.png)

**Comment by aileennoonan** [comment]
I want this content here to appear as a list of key selling points:
![image](https://user-images.githubusercontent.com/25756782/26999326-2aee9de2-4dda-11e7-89f8-a482fec79631.png)

**Comment by 1001hz** [comment]
Doneski! You just have to use bullet list in the new WYSIWYG and the ticks appear. Might be a bit too many items though. That's a content thing anyway.

**Comment by aileennoonan** [comment]
Loving the ticks but just from a design point of view the positioning of the image versus the list of ticks is a little off. Could we either:
- have the top of the list flush with the top of the image
- centre the image into the middle of the list

Again - tell me if this is too much hassle.

**Comment by 1001hz** [comment]
Aligned ticks to top of image. Done.

**Comment by aileennoonan** [comment]
Thanks!
