### ISSUE TITLE
Idea for FAQ page (nice to have, not essential if it's going to be hard/take a long time)

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#23]
![image](https://user-images.githubusercontent.com/25756782/26999598-282ca1c4-4de1-11e7-89e7-e55822e3efb0.png)

We will have a pretty comprehensive FAQ page. It would be awesome to have this accordion style. No hassle if it's a hassle :)

**Comment by 1001hz** [comment]
There's a FAQ section on the left in admin now. Add or delete just like staff etc. I made a new page under About Us and used the "shortcode" (Wordpress term) to pull in the faqs. You'll see [faqs] in the content of that page (just like [quote] or [staff]) and you can put content above or below it. If you happy with the style let me know and I'll close off the ticket

**Comment by aileennoonan** [comment]
Looks AWESOME! And so easy to use. Thanks :) You can close off.
