### ISSUE TITLE
How do I access the content on Contact page?

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#26]
The fax number is wrong so I went in to change it but the contact page just has the book an appointment thing, not the content. 

FYI - the fax number is also wrong in the footer. Do I have access to the footer?

**Comment by 1001hz** [comment]
Contact details are managed for the whole site in the settings section.
Just change it there and it should update in all the places around the site.

**Comment by aileennoonan** [comment]
Doh!! You told me this before. Sorry.. I totally forgot!
