### ISSUE TITLE
Eoin noticed something so blame him

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#28]
He was playing around with the website this morning and said he found that a few times when he tried to click on buttons, nothing happened e.g. when you hover over About Us the button turns blue but the click only only works when you are in the middle of the button (and the cursor turns into a hand). Is it possible to make the whole button clickable?

**Comment by aileennoonan** [comment]
Also.. the services button on the carousel is a dead link at the moment. Do I have access to buttons or is that something that is at your end?

**Comment by 1001hz** [comment]
What's that guy's problem! OK those 2 things should be fixed. The services button in the homepage carousel is hard coded at the moment. Do you need the ability to change and update these buttons? If not then can we close off this one?

**Comment by aileennoonan** [comment]
Thanks John. I won't need to be fiddling with these buttons very often so no point hard coding.
