### ISSUE TITLE
Sisters need to delay the content side of things a little bit

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#29]
Hey John,

I put together a content plan during the week and sent it to my sisters as I need their input now. They pretty much freaked out and said they are going to keep the golden pages site going until the end of September so it gives them more time!! One of them just got back from hols and the other is going on Thursday so I think it's just bad timing. 

So... we will still aim to have it finished from your perspective by the end of the month. When I'm working on it in August and Sept.. would you be available for the odd random Q if I get very stuck or if something breaks or becomes glitchy?

**Comment by 1001hz** [comment]
Yeah cool no probs. There's usually a few teething problems anyway. So
we'll still plow ahead and get it finished (apart from content) as soon as
we can. You can get the content sorted by September and after that I'll see
where I am and make some time to do the switchover.

**Comment by aileennoonan** [comment]
You're a lovely boy!
