### ISSUE TITLE
Book an appointment in the footer

### ISSUE THREAD

**Issue by aileennoonan** [1001hz/wpnoonan#30]
Hey John,

Can you put 'Book an appointment' in the footer? I don't mind whether it's just a line in the quick links or if it's a button. 

Cheers,
Aileen

**Comment by aileennoonan** [comment]
Or maybe you will have another suggestion. The reason I'm asking this is because when you are in pages like 'About Us' on mobile, there is no book an appointment call to action available. You would have to click back to the homepage to find it.

**Comment by 1001hz** [comment]
I've put in the Book an appointment full width section before the footer on any pages with the 2 col template like on the other pages. Best to keep it consistent on all the pages.

**Comment by aileennoonan** [comment]
Sweet as a nut Joey!
