### ISSUE TITLE
Staff list page header spacing

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#6]
Breadcrumb spacing looks fine on the blog now. However, there is a big gap on the staff page between 'We're passionate about what we do' and the first staff profile.

**Comment by 1001hz** [comment]
Looks ok now I think

**Comment by aileennoonan** [comment]
Eeeek. I realise I'm a pain in the arse but this still doesn't look right to me. :/

- There is too much of a gap between Our Team and the blurb. Can you make it a bit smaller?
- Can you make the blurb black, not blue
- Can there be an ever so slightly bigger gap between the blurb and the profiles?

**Comment by 1001hz** [comment]
Done

**Comment by aileennoonan** [comment]
This is perfect! You can close this off now :)
