### ISSUE TITLE
Staff page section gap

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#7]
When you click into a staff profile there is also a big gap between the photo, the About X sextion and the X full bio sections.

**Comment by 1001hz** [comment]
That's the same gap as the sections on the homepage but looks bigger because the sections are the same color. You want to reduce the gap to half this?

**Comment by aileennoonan** [comment]
Half the gap sounds good

**Comment by 1001hz** [comment]
Done?

**Comment by aileennoonan** [comment]
Done!
