### ISSUE TITLE
About author section

### ISSUE THREAD

**Issue by 1001hz** [1001hz/wpnoonan#9]
You asked me this a couple of weeks back:"Also the last part about Claire is doing what the next staff section is meant to do. Do you want to be able to put in extra info about the author on a per post basis? I can make a way for that that will be more structured than just adding it to the article content if you want". My answer: You're right there was a bit of repetition. However, the 'About Claire' section is static and always says the same thing whereas at the end of a blog post you might want to highlight a niche skillset of the physio in question to line up with the theme of the blog. I see you have now put that bit into it's own section below the 'about claire' section with a Book Now button. Is that the structured section you were talking about? If so, can we move it above the 'about the author' section? And how does that section get edited?

**Comment by 1001hz** [comment]
I will move the CTA with the contact message above the About the author section. You edit this in the staff edit screen, the field is Contact Message, under Full Bio. Do you want an extra section for How We Can Help or something but changing on a per blog article basis? If so is it just a text field or are you planning on putting in staff details. If you are then that means 3 different sections about the same staff member at the foot of each article.

**Comment by aileennoonan** [comment]
As discussed last night, we only need one section about the staff member at the end of each blog post...preferably with a custom message that highlights certain attributes of that staff member which relate to that particular blog topic - it's just the make the sell a bit more persuasive.

**Comment by 1001hz** [comment]
New field in each blog post called Author Selling Point. This will go into the About the author section on a per blog article basis. Done?

**Comment by aileennoonan** [comment]
Very cool!

This is great. How do I remove the text from the Book with Claire section at the end of the post?

**Comment by 1001hz** [comment]
Edit the staff member and there's a field called "Contact Message" that you can delete if you want.

**Comment by aileennoonan** [comment]
Awesome thanks! You can close this off now.
